resolver: lts-8.6
packages:
- '.'
- '../../libs/bilge'
- '../../libs/brig-types'
- '../../libs/cassandra-util'
- '../../libs/galley-types'
- '../../libs/gundeck-types'
- '../../libs/http-client-openssl-ext'
- '../../libs/metrics-core'
- '../../libs/metrics-wai'
- '../../libs/tasty-cannon'
- '../../libs/types-common'
- '../../libs/wai-utilities'

flags:
  types-common:
    cql: True
    protobuf: True
    arbitrary: True

extra-deps:
- aeson-1.1.1.0
- data-checked-0.3
- data-textual-0.3.0.2
- data-timeout-0.3
- raw-strings-qq-1.0.2
- text-latin1-0.3
- text-printer-0.5
- wai-middleware-gunzip-0.0.2
extra-package-dbs: []
