resolver: lts-8.19
packages:
- '.'
- '../../libs/api-bot'
- '../../libs/api-client'
- '../../libs/bilge'
- '../../libs/brig-types'
- '../../libs/cargohold-types'
- '../../libs/galley-types'
- '../../libs/gundeck-types'
- '../../libs/metrics-core'
- '../../libs/types-common'

extra-deps:
- mime-0.4.0.2
- cryptobox-haskell-0.1.1
flags:
  types-common:
    protobuf: True
    arbitrary: True
